/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ServiceChannel.Api.Client.OpenAPIDateConverter;

namespace ServiceChannel.Api.Model
{
    /// <summary>
    /// SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest
    /// </summary>
    [DataContract(Name = "ServiceChannel.Services.Messaging.RefrigerantTracking.LeakDetectorAuditAddUpdateRequest")]
    public partial class SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest : IEquatable<SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest>, IValidatableObject
    {
        /// <summary>
        /// Defines ServiceType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ServiceTypeEnum
        {
            /// <summary>
            /// Enum Audit for value: Audit
            /// </summary>
            [EnumMember(Value = "Audit")]
            Audit = 1,

            /// <summary>
            /// Enum Inspection for value: Inspection
            /// </summary>
            [EnumMember(Value = "Inspection")]
            Inspection = 2

        }


        /// <summary>
        /// Gets or Sets ServiceType
        /// </summary>
        [DataMember(Name = "ServiceType", EmitDefaultValue = false)]
        public ServiceTypeEnum? ServiceType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="leakDetectorId">leakDetectorId.</param>
        /// <param name="alarmSetPoint">alarmSetPoint.</param>
        /// <param name="detectionLimit">detectionLimit.</param>
        /// <param name="recId">recId.</param>
        /// <param name="serviceDate">serviceDate.</param>
        /// <param name="serviceType">serviceType.</param>
        /// <param name="serviceDescription">serviceDescription.</param>
        /// <param name="locationId">locationId.</param>
        public SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest(int id = default(int), int leakDetectorId = default(int), double alarmSetPoint = default(double), double detectionLimit = default(double), int recId = default(int), DateTime serviceDate = default(DateTime), ServiceTypeEnum? serviceType = default(ServiceTypeEnum?), string serviceDescription = default(string), int locationId = default(int))
        {
            this.Id = id;
            this.LeakDetectorId = leakDetectorId;
            this.AlarmSetPoint = alarmSetPoint;
            this.DetectionLimit = detectionLimit;
            this.RecId = recId;
            this.ServiceDate = serviceDate;
            this.ServiceType = serviceType;
            this.ServiceDescription = serviceDescription;
            this.LocationId = locationId;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "Id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets LeakDetectorId
        /// </summary>
        [DataMember(Name = "LeakDetectorId", EmitDefaultValue = false)]
        public int LeakDetectorId { get; set; }

        /// <summary>
        /// Gets or Sets AlarmSetPoint
        /// </summary>
        [DataMember(Name = "AlarmSetPoint", EmitDefaultValue = false)]
        public double AlarmSetPoint { get; set; }

        /// <summary>
        /// Gets or Sets DetectionLimit
        /// </summary>
        [DataMember(Name = "DetectionLimit", EmitDefaultValue = false)]
        public double DetectionLimit { get; set; }

        /// <summary>
        /// Gets or Sets RecId
        /// </summary>
        [DataMember(Name = "RecId", EmitDefaultValue = false)]
        public int RecId { get; set; }

        /// <summary>
        /// Gets or Sets ServiceDate
        /// </summary>
        [DataMember(Name = "ServiceDate", EmitDefaultValue = false)]
        public DateTime ServiceDate { get; set; }

        /// <summary>
        /// Gets or Sets ServiceDescription
        /// </summary>
        [DataMember(Name = "ServiceDescription", EmitDefaultValue = false)]
        public string ServiceDescription { get; set; }

        /// <summary>
        /// Gets or Sets LocationId
        /// </summary>
        [DataMember(Name = "LocationId", EmitDefaultValue = false)]
        public int LocationId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  LeakDetectorId: ").Append(LeakDetectorId).Append("\n");
            sb.Append("  AlarmSetPoint: ").Append(AlarmSetPoint).Append("\n");
            sb.Append("  DetectionLimit: ").Append(DetectionLimit).Append("\n");
            sb.Append("  RecId: ").Append(RecId).Append("\n");
            sb.Append("  ServiceDate: ").Append(ServiceDate).Append("\n");
            sb.Append("  ServiceType: ").Append(ServiceType).Append("\n");
            sb.Append("  ServiceDescription: ").Append(ServiceDescription).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingRefrigerantTrackingLeakDetectorAuditAddUpdateRequest input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.LeakDetectorId == input.LeakDetectorId ||
                    this.LeakDetectorId.Equals(input.LeakDetectorId)
                ) && 
                (
                    this.AlarmSetPoint == input.AlarmSetPoint ||
                    this.AlarmSetPoint.Equals(input.AlarmSetPoint)
                ) && 
                (
                    this.DetectionLimit == input.DetectionLimit ||
                    this.DetectionLimit.Equals(input.DetectionLimit)
                ) && 
                (
                    this.RecId == input.RecId ||
                    this.RecId.Equals(input.RecId)
                ) && 
                (
                    this.ServiceDate == input.ServiceDate ||
                    (this.ServiceDate != null &&
                    this.ServiceDate.Equals(input.ServiceDate))
                ) && 
                (
                    this.ServiceType == input.ServiceType ||
                    this.ServiceType.Equals(input.ServiceType)
                ) && 
                (
                    this.ServiceDescription == input.ServiceDescription ||
                    (this.ServiceDescription != null &&
                    this.ServiceDescription.Equals(input.ServiceDescription))
                ) && 
                (
                    this.LocationId == input.LocationId ||
                    this.LocationId.Equals(input.LocationId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                hashCode = (hashCode * 59) + this.LeakDetectorId.GetHashCode();
                hashCode = (hashCode * 59) + this.AlarmSetPoint.GetHashCode();
                hashCode = (hashCode * 59) + this.DetectionLimit.GetHashCode();
                hashCode = (hashCode * 59) + this.RecId.GetHashCode();
                if (this.ServiceDate != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.ServiceType.GetHashCode();
                if (this.ServiceDescription != null)
                {
                    hashCode = (hashCode * 59) + this.ServiceDescription.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.LocationId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
