/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ServiceChannel.Api.Client.OpenAPIDateConverter;

namespace ServiceChannel.Api.Model
{
    /// <summary>
    /// Object containing the details of resolution codes and root causes of a work order.
    /// </summary>
    [DataContract(Name = "ServiceChannel.Services.Messaging.ResolutionCodes.WorkOrderResolutionInfo")]
    public partial class SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo : IEquatable<SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo" /> class.
        /// </summary>
        /// <param name="resolutionCodes">Resolution codes of a work order..</param>
        /// <param name="rootCause">rootCause.</param>
        /// <param name="rootCauses">Root causes of a work order returned for users with access to asset categories..</param>
        public SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo(List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionCode> resolutionCodes = default(List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionCode>), SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause rootCause = default(SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause), List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause> rootCauses = default(List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause>))
        {
            this.ResolutionCodes = resolutionCodes;
            this.RootCause = rootCause;
            this.RootCauses = rootCauses;
        }

        /// <summary>
        /// Resolution codes of a work order.
        /// </summary>
        /// <value>Resolution codes of a work order.</value>
        [DataMember(Name = "resolutionCodes", EmitDefaultValue = false)]
        public List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionCode> ResolutionCodes { get; set; }

        /// <summary>
        /// Gets or Sets RootCause
        /// </summary>
        [DataMember(Name = "rootCause", EmitDefaultValue = false)]
        public SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause RootCause { get; set; }

        /// <summary>
        /// Root causes of a work order returned for users with access to asset categories.
        /// </summary>
        /// <value>Root causes of a work order returned for users with access to asset categories.</value>
        [DataMember(Name = "rootCauses", EmitDefaultValue = false)]
        public List<SCServiceChannelServicesMessagingResolutionCodesWorkOrderRootCause> RootCauses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo {\n");
            sb.Append("  ResolutionCodes: ").Append(ResolutionCodes).Append("\n");
            sb.Append("  RootCause: ").Append(RootCause).Append("\n");
            sb.Append("  RootCauses: ").Append(RootCauses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingResolutionCodesWorkOrderResolutionInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ResolutionCodes == input.ResolutionCodes ||
                    this.ResolutionCodes != null &&
                    input.ResolutionCodes != null &&
                    this.ResolutionCodes.SequenceEqual(input.ResolutionCodes)
                ) && 
                (
                    this.RootCause == input.RootCause ||
                    (this.RootCause != null &&
                    this.RootCause.Equals(input.RootCause))
                ) && 
                (
                    this.RootCauses == input.RootCauses ||
                    this.RootCauses != null &&
                    input.RootCauses != null &&
                    this.RootCauses.SequenceEqual(input.RootCauses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ResolutionCodes != null)
                {
                    hashCode = (hashCode * 59) + this.ResolutionCodes.GetHashCode();
                }
                if (this.RootCause != null)
                {
                    hashCode = (hashCode * 59) + this.RootCause.GetHashCode();
                }
                if (this.RootCauses != null)
                {
                    hashCode = (hashCode * 59) + this.RootCauses.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
