/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ServiceChannel.Api.Client.OpenAPIDateConverter;

namespace ServiceChannel.Api.Model
{
    /// <summary>
    /// SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable
    /// </summary>
    [DataContract(Name = "ServiceChannel.Services.Messaging.RefrigerantTracking.UpdateLeakImmeasurable")]
    public partial class SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable : IEquatable<SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="repairDate">repairDate.</param>
        /// <param name="initialVerificationDate">initialVerificationDate.</param>
        /// <param name="initialVerificationMethod">initialVerificationMethod.</param>
        /// <param name="followUpVerificationDate">followUpVerificationDate.</param>
        /// <param name="followUpVerificationMethod">followUpVerificationMethod.</param>
        /// <param name="actionCodeId">actionCodeId.</param>
        /// <param name="faultCodeId">faultCodeId.</param>
        /// <param name="leakLocationId">leakLocationId.</param>
        /// <param name="notes">notes.</param>
        public SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable(int id = default(int), DateTime repairDate = default(DateTime), DateTime initialVerificationDate = default(DateTime), int initialVerificationMethod = default(int), DateTime followUpVerificationDate = default(DateTime), int followUpVerificationMethod = default(int), int actionCodeId = default(int), int faultCodeId = default(int), int leakLocationId = default(int), List<string> notes = default(List<string>))
        {
            this.Id = id;
            this.RepairDate = repairDate;
            this.InitialVerificationDate = initialVerificationDate;
            this.InitialVerificationMethod = initialVerificationMethod;
            this.FollowUpVerificationDate = followUpVerificationDate;
            this.FollowUpVerificationMethod = followUpVerificationMethod;
            this.ActionCodeId = actionCodeId;
            this.FaultCodeId = faultCodeId;
            this.LeakLocationId = leakLocationId;
            this.Notes = notes;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "Id", EmitDefaultValue = false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets RepairDate
        /// </summary>
        [DataMember(Name = "RepairDate", EmitDefaultValue = false)]
        public DateTime RepairDate { get; set; }

        /// <summary>
        /// Gets or Sets InitialVerificationDate
        /// </summary>
        [DataMember(Name = "InitialVerificationDate", EmitDefaultValue = false)]
        public DateTime InitialVerificationDate { get; set; }

        /// <summary>
        /// Gets or Sets InitialVerificationMethod
        /// </summary>
        [DataMember(Name = "InitialVerificationMethod", EmitDefaultValue = false)]
        public int InitialVerificationMethod { get; set; }

        /// <summary>
        /// Gets or Sets FollowUpVerificationDate
        /// </summary>
        [DataMember(Name = "FollowUpVerificationDate", EmitDefaultValue = false)]
        public DateTime FollowUpVerificationDate { get; set; }

        /// <summary>
        /// Gets or Sets FollowUpVerificationMethod
        /// </summary>
        [DataMember(Name = "FollowUpVerificationMethod", EmitDefaultValue = false)]
        public int FollowUpVerificationMethod { get; set; }

        /// <summary>
        /// Gets or Sets ActionCodeId
        /// </summary>
        [DataMember(Name = "ActionCodeId", EmitDefaultValue = false)]
        public int ActionCodeId { get; set; }

        /// <summary>
        /// Gets or Sets FaultCodeId
        /// </summary>
        [DataMember(Name = "FaultCodeId", EmitDefaultValue = false)]
        public int FaultCodeId { get; set; }

        /// <summary>
        /// Gets or Sets LeakLocationId
        /// </summary>
        [DataMember(Name = "LeakLocationId", EmitDefaultValue = false)]
        public int LeakLocationId { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name = "Notes", EmitDefaultValue = false)]
        public List<string> Notes { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  RepairDate: ").Append(RepairDate).Append("\n");
            sb.Append("  InitialVerificationDate: ").Append(InitialVerificationDate).Append("\n");
            sb.Append("  InitialVerificationMethod: ").Append(InitialVerificationMethod).Append("\n");
            sb.Append("  FollowUpVerificationDate: ").Append(FollowUpVerificationDate).Append("\n");
            sb.Append("  FollowUpVerificationMethod: ").Append(FollowUpVerificationMethod).Append("\n");
            sb.Append("  ActionCodeId: ").Append(ActionCodeId).Append("\n");
            sb.Append("  FaultCodeId: ").Append(FaultCodeId).Append("\n");
            sb.Append("  LeakLocationId: ").Append(LeakLocationId).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable instances are equal
        /// </summary>
        /// <param name="input">Instance of SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingRefrigerantTrackingUpdateLeakImmeasurable input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Id == input.Id ||
                    this.Id.Equals(input.Id)
                ) && 
                (
                    this.RepairDate == input.RepairDate ||
                    (this.RepairDate != null &&
                    this.RepairDate.Equals(input.RepairDate))
                ) && 
                (
                    this.InitialVerificationDate == input.InitialVerificationDate ||
                    (this.InitialVerificationDate != null &&
                    this.InitialVerificationDate.Equals(input.InitialVerificationDate))
                ) && 
                (
                    this.InitialVerificationMethod == input.InitialVerificationMethod ||
                    this.InitialVerificationMethod.Equals(input.InitialVerificationMethod)
                ) && 
                (
                    this.FollowUpVerificationDate == input.FollowUpVerificationDate ||
                    (this.FollowUpVerificationDate != null &&
                    this.FollowUpVerificationDate.Equals(input.FollowUpVerificationDate))
                ) && 
                (
                    this.FollowUpVerificationMethod == input.FollowUpVerificationMethod ||
                    this.FollowUpVerificationMethod.Equals(input.FollowUpVerificationMethod)
                ) && 
                (
                    this.ActionCodeId == input.ActionCodeId ||
                    this.ActionCodeId.Equals(input.ActionCodeId)
                ) && 
                (
                    this.FaultCodeId == input.FaultCodeId ||
                    this.FaultCodeId.Equals(input.FaultCodeId)
                ) && 
                (
                    this.LeakLocationId == input.LeakLocationId ||
                    this.LeakLocationId.Equals(input.LeakLocationId)
                ) && 
                (
                    this.Notes == input.Notes ||
                    this.Notes != null &&
                    input.Notes != null &&
                    this.Notes.SequenceEqual(input.Notes)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Id.GetHashCode();
                if (this.RepairDate != null)
                {
                    hashCode = (hashCode * 59) + this.RepairDate.GetHashCode();
                }
                if (this.InitialVerificationDate != null)
                {
                    hashCode = (hashCode * 59) + this.InitialVerificationDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.InitialVerificationMethod.GetHashCode();
                if (this.FollowUpVerificationDate != null)
                {
                    hashCode = (hashCode * 59) + this.FollowUpVerificationDate.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.FollowUpVerificationMethod.GetHashCode();
                hashCode = (hashCode * 59) + this.ActionCodeId.GetHashCode();
                hashCode = (hashCode * 59) + this.FaultCodeId.GetHashCode();
                hashCode = (hashCode * 59) + this.LeakLocationId.GetHashCode();
                if (this.Notes != null)
                {
                    hashCode = (hashCode * 59) + this.Notes.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
