/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ServiceChannel.Api.Client.OpenAPIDateConverter;

namespace ServiceChannel.Api.Model
{
    /// <summary>
    /// SCServiceChannelServicesMessagingFilterItemSystemInt32
    /// </summary>
    [DataContract(Name = "ServiceChannel.Services.Messaging.FilterItem[System.Int32]")]
    public partial class SCServiceChannelServicesMessagingFilterItemSystemInt32 : IEquatable<SCServiceChannelServicesMessagingFilterItemSystemInt32>, IValidatableObject
    {
        /// <summary>
        /// Defines OperationType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationTypeEnum
        {
            /// <summary>
            /// Enum Equal for value: Equal
            /// </summary>
            [EnumMember(Value = "Equal")]
            Equal = 1,

            /// <summary>
            /// Enum NotEqual for value: NotEqual
            /// </summary>
            [EnumMember(Value = "NotEqual")]
            NotEqual = 2,

            /// <summary>
            /// Enum Greater for value: Greater
            /// </summary>
            [EnumMember(Value = "Greater")]
            Greater = 3,

            /// <summary>
            /// Enum Less for value: Less
            /// </summary>
            [EnumMember(Value = "Less")]
            Less = 4,

            /// <summary>
            /// Enum Like for value: Like
            /// </summary>
            [EnumMember(Value = "Like")]
            Like = 5,

            /// <summary>
            /// Enum StartsWith for value: StartsWith
            /// </summary>
            [EnumMember(Value = "StartsWith")]
            StartsWith = 6,

            /// <summary>
            /// Enum GreaterOrEqual for value: GreaterOrEqual
            /// </summary>
            [EnumMember(Value = "GreaterOrEqual")]
            GreaterOrEqual = 7,

            /// <summary>
            /// Enum LessOrEqual for value: LessOrEqual
            /// </summary>
            [EnumMember(Value = "LessOrEqual")]
            LessOrEqual = 8

        }


        /// <summary>
        /// Gets or Sets OperationType
        /// </summary>
        [DataMember(Name = "OperationType", EmitDefaultValue = false)]
        public OperationTypeEnum? OperationType { get; set; }
        /// <summary>
        /// Defines LogicalOperationType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LogicalOperationTypeEnum
        {
            /// <summary>
            /// Enum Or for value: Or
            /// </summary>
            [EnumMember(Value = "Or")]
            Or = 1,

            /// <summary>
            /// Enum And for value: And
            /// </summary>
            [EnumMember(Value = "And")]
            And = 2

        }


        /// <summary>
        /// Gets or Sets LogicalOperationType
        /// </summary>
        [DataMember(Name = "LogicalOperationType", EmitDefaultValue = false)]
        public LogicalOperationTypeEnum? LogicalOperationType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SCServiceChannelServicesMessagingFilterItemSystemInt32" /> class.
        /// </summary>
        /// <param name="operationType">operationType.</param>
        /// <param name="logicalOperationType">logicalOperationType.</param>
        /// <param name="connectedFilterItemName">connectedFilterItemName.</param>
        /// <param name="filterValue">filterValue.</param>
        public SCServiceChannelServicesMessagingFilterItemSystemInt32(OperationTypeEnum? operationType = default(OperationTypeEnum?), LogicalOperationTypeEnum? logicalOperationType = default(LogicalOperationTypeEnum?), string connectedFilterItemName = default(string), int filterValue = default(int))
        {
            this.OperationType = operationType;
            this.LogicalOperationType = logicalOperationType;
            this.ConnectedFilterItemName = connectedFilterItemName;
            this.FilterValue = filterValue;
        }

        /// <summary>
        /// Gets or Sets ConnectedFilterItemName
        /// </summary>
        [DataMember(Name = "ConnectedFilterItemName", EmitDefaultValue = false)]
        public string ConnectedFilterItemName { get; set; }

        /// <summary>
        /// Gets or Sets FilterValue
        /// </summary>
        [DataMember(Name = "FilterValue", EmitDefaultValue = false)]
        public int FilterValue { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingFilterItemSystemInt32 {\n");
            sb.Append("  OperationType: ").Append(OperationType).Append("\n");
            sb.Append("  LogicalOperationType: ").Append(LogicalOperationType).Append("\n");
            sb.Append("  ConnectedFilterItemName: ").Append(ConnectedFilterItemName).Append("\n");
            sb.Append("  FilterValue: ").Append(FilterValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SCServiceChannelServicesMessagingFilterItemSystemInt32);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingFilterItemSystemInt32 instances are equal
        /// </summary>
        /// <param name="input">Instance of SCServiceChannelServicesMessagingFilterItemSystemInt32 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingFilterItemSystemInt32 input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OperationType == input.OperationType ||
                    this.OperationType.Equals(input.OperationType)
                ) && 
                (
                    this.LogicalOperationType == input.LogicalOperationType ||
                    this.LogicalOperationType.Equals(input.LogicalOperationType)
                ) && 
                (
                    this.ConnectedFilterItemName == input.ConnectedFilterItemName ||
                    (this.ConnectedFilterItemName != null &&
                    this.ConnectedFilterItemName.Equals(input.ConnectedFilterItemName))
                ) && 
                (
                    this.FilterValue == input.FilterValue ||
                    this.FilterValue.Equals(input.FilterValue)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.OperationType.GetHashCode();
                hashCode = (hashCode * 59) + this.LogicalOperationType.GetHashCode();
                if (this.ConnectedFilterItemName != null)
                {
                    hashCode = (hashCode * 59) + this.ConnectedFilterItemName.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.FilterValue.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
