/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = ServiceChannel.Api.Client.OpenAPIDateConverter;

namespace ServiceChannel.Api.Model
{
    /// <summary>
    /// SCServiceChannelServicesMessagingProposalsProposalCategoryColumn
    /// </summary>
    [DataContract(Name = "ServiceChannel.Services.Messaging.Proposals.ProposalCategoryColumn")]
    public partial class SCServiceChannelServicesMessagingProposalsProposalCategoryColumn : IEquatable<SCServiceChannelServicesMessagingProposalsProposalCategoryColumn>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SCServiceChannelServicesMessagingProposalsProposalCategoryColumn" /> class.
        /// </summary>
        /// <param name="dataField">dataField.</param>
        /// <param name="dataType">dataType.</param>
        /// <param name="isDescriptionColumn">isDescriptionColumn (default to false).</param>
        /// <param name="isMarkUpColumn">isMarkUpColumn (default to false).</param>
        /// <param name="isUserReservedColumn">isUserReservedColumn (default to false).</param>
        /// <param name="name">name.</param>
        /// <param name="description">description.</param>
        /// <param name="isActive">isActive (default to false).</param>
        /// <param name="sortOrder">sortOrder.</param>
        public SCServiceChannelServicesMessagingProposalsProposalCategoryColumn(string dataField = default(string), string dataType = default(string), bool isDescriptionColumn = false, bool isMarkUpColumn = false, bool isUserReservedColumn = false, string name = default(string), string description = default(string), bool isActive = false, int sortOrder = default(int))
        {
            this.DataField = dataField;
            this.DataType = dataType;
            this.IsDescriptionColumn = isDescriptionColumn;
            this.IsMarkUpColumn = isMarkUpColumn;
            this.IsUserReservedColumn = isUserReservedColumn;
            this.Name = name;
            this.Description = description;
            this.IsActive = isActive;
            this.SortOrder = sortOrder;
        }

        /// <summary>
        /// Gets or Sets DataField
        /// </summary>
        [DataMember(Name = "DataField", EmitDefaultValue = false)]
        public string DataField { get; set; }

        /// <summary>
        /// Gets or Sets DataType
        /// </summary>
        [DataMember(Name = "DataType", EmitDefaultValue = false)]
        public string DataType { get; set; }

        /// <summary>
        /// Gets or Sets IsDescriptionColumn
        /// </summary>
        [DataMember(Name = "IsDescriptionColumn", EmitDefaultValue = true)]
        public bool IsDescriptionColumn { get; set; }

        /// <summary>
        /// Gets or Sets IsMarkUpColumn
        /// </summary>
        [DataMember(Name = "IsMarkUpColumn", EmitDefaultValue = true)]
        public bool IsMarkUpColumn { get; set; }

        /// <summary>
        /// Gets or Sets IsUserReservedColumn
        /// </summary>
        [DataMember(Name = "IsUserReservedColumn", EmitDefaultValue = true)]
        public bool IsUserReservedColumn { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "Name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name = "Description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [DataMember(Name = "IsActive", EmitDefaultValue = true)]
        public bool IsActive { get; set; }

        /// <summary>
        /// Gets or Sets SortOrder
        /// </summary>
        [DataMember(Name = "SortOrder", EmitDefaultValue = false)]
        public int SortOrder { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingProposalsProposalCategoryColumn {\n");
            sb.Append("  DataField: ").Append(DataField).Append("\n");
            sb.Append("  DataType: ").Append(DataType).Append("\n");
            sb.Append("  IsDescriptionColumn: ").Append(IsDescriptionColumn).Append("\n");
            sb.Append("  IsMarkUpColumn: ").Append(IsMarkUpColumn).Append("\n");
            sb.Append("  IsUserReservedColumn: ").Append(IsUserReservedColumn).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  SortOrder: ").Append(SortOrder).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SCServiceChannelServicesMessagingProposalsProposalCategoryColumn);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingProposalsProposalCategoryColumn instances are equal
        /// </summary>
        /// <param name="input">Instance of SCServiceChannelServicesMessagingProposalsProposalCategoryColumn to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingProposalsProposalCategoryColumn input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.DataField == input.DataField ||
                    (this.DataField != null &&
                    this.DataField.Equals(input.DataField))
                ) && 
                (
                    this.DataType == input.DataType ||
                    (this.DataType != null &&
                    this.DataType.Equals(input.DataType))
                ) && 
                (
                    this.IsDescriptionColumn == input.IsDescriptionColumn ||
                    this.IsDescriptionColumn.Equals(input.IsDescriptionColumn)
                ) && 
                (
                    this.IsMarkUpColumn == input.IsMarkUpColumn ||
                    this.IsMarkUpColumn.Equals(input.IsMarkUpColumn)
                ) && 
                (
                    this.IsUserReservedColumn == input.IsUserReservedColumn ||
                    this.IsUserReservedColumn.Equals(input.IsUserReservedColumn)
                ) && 
                (
                    this.Name == input.Name ||
                    (this.Name != null &&
                    this.Name.Equals(input.Name))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                ) && 
                (
                    this.IsActive == input.IsActive ||
                    this.IsActive.Equals(input.IsActive)
                ) && 
                (
                    this.SortOrder == input.SortOrder ||
                    this.SortOrder.Equals(input.SortOrder)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DataField != null)
                {
                    hashCode = (hashCode * 59) + this.DataField.GetHashCode();
                }
                if (this.DataType != null)
                {
                    hashCode = (hashCode * 59) + this.DataType.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsDescriptionColumn.GetHashCode();
                hashCode = (hashCode * 59) + this.IsMarkUpColumn.GetHashCode();
                hashCode = (hashCode * 59) + this.IsUserReservedColumn.GetHashCode();
                if (this.Name != null)
                {
                    hashCode = (hashCode * 59) + this.Name.GetHashCode();
                }
                if (this.Description != null)
                {
                    hashCode = (hashCode * 59) + this.Description.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.IsActive.GetHashCode();
                hashCode = (hashCode * 59) + this.SortOrder.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
