/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text.Json;
using ServiceChannel.OpenAPIGenerated.Api.Converters;

namespace ServiceChannel.OpenAPIGenerated.Api.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public class SCServiceChannelServicesMessagingLandingUserLandingData : IEquatable<SCServiceChannelServicesMessagingLandingUserLandingData>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="Id", EmitDefaultValue=true)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets ENearEta
        /// </summary>
        [DataMember(Name="ENearEta", EmitDefaultValue=true)]
        public int ENearEta { get; set; }

        /// <summary>
        /// Gets or Sets EDispatchNotConfirmed
        /// </summary>
        [DataMember(Name="EDispatchNotConfirmed", EmitDefaultValue=true)]
        public int EDispatchNotConfirmed { get; set; }

        /// <summary>
        /// Gets or Sets EDeclined
        /// </summary>
        [DataMember(Name="EDeclined", EmitDefaultValue=true)]
        public int EDeclined { get; set; }

        /// <summary>
        /// Gets or Sets EProposalPending
        /// </summary>
        [DataMember(Name="EProposalPending", EmitDefaultValue=true)]
        public int EProposalPending { get; set; }

        /// <summary>
        /// Gets or Sets EProposalPendingApproval
        /// </summary>
        [DataMember(Name="EProposalPendingApproval", EmitDefaultValue=true)]
        public int EProposalPendingApproval { get; set; }

        /// <summary>
        /// Gets or Sets NeNearEta
        /// </summary>
        [DataMember(Name="NeNearEta", EmitDefaultValue=true)]
        public int NeNearEta { get; set; }

        /// <summary>
        /// Gets or Sets NeDispatchNotConfirmed
        /// </summary>
        [DataMember(Name="NeDispatchNotConfirmed", EmitDefaultValue=true)]
        public int NeDispatchNotConfirmed { get; set; }

        /// <summary>
        /// Gets or Sets NeDeclined
        /// </summary>
        [DataMember(Name="NeDeclined", EmitDefaultValue=true)]
        public int NeDeclined { get; set; }

        /// <summary>
        /// Gets or Sets NeProposalPending
        /// </summary>
        [DataMember(Name="NeProposalPending", EmitDefaultValue=true)]
        public int NeProposalPending { get; set; }

        /// <summary>
        /// Gets or Sets NeProposalPendingApproval
        /// </summary>
        [DataMember(Name="NeProposalPendingApproval", EmitDefaultValue=true)]
        public int NeProposalPendingApproval { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SCServiceChannelServicesMessagingLandingUserLandingData {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ENearEta: ").Append(ENearEta).Append("\n");
            sb.Append("  EDispatchNotConfirmed: ").Append(EDispatchNotConfirmed).Append("\n");
            sb.Append("  EDeclined: ").Append(EDeclined).Append("\n");
            sb.Append("  EProposalPending: ").Append(EProposalPending).Append("\n");
            sb.Append("  EProposalPendingApproval: ").Append(EProposalPendingApproval).Append("\n");
            sb.Append("  NeNearEta: ").Append(NeNearEta).Append("\n");
            sb.Append("  NeDispatchNotConfirmed: ").Append(NeDispatchNotConfirmed).Append("\n");
            sb.Append("  NeDeclined: ").Append(NeDeclined).Append("\n");
            sb.Append("  NeProposalPending: ").Append(NeProposalPending).Append("\n");
            sb.Append("  NeProposalPendingApproval: ").Append(NeProposalPendingApproval).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            var options = new JsonSerializerOptions
            {
                WriteIndented = true
            };

            return JsonSerializer.Serialize(this, options);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((SCServiceChannelServicesMessagingLandingUserLandingData)obj);
        }

        /// <summary>
        /// Returns true if SCServiceChannelServicesMessagingLandingUserLandingData instances are equal
        /// </summary>
        /// <param name="other">Instance of SCServiceChannelServicesMessagingLandingUserLandingData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SCServiceChannelServicesMessagingLandingUserLandingData other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    
                    Id.Equals(other.Id)
                ) && 
                (
                    ENearEta == other.ENearEta ||
                    
                    ENearEta.Equals(other.ENearEta)
                ) && 
                (
                    EDispatchNotConfirmed == other.EDispatchNotConfirmed ||
                    
                    EDispatchNotConfirmed.Equals(other.EDispatchNotConfirmed)
                ) && 
                (
                    EDeclined == other.EDeclined ||
                    
                    EDeclined.Equals(other.EDeclined)
                ) && 
                (
                    EProposalPending == other.EProposalPending ||
                    
                    EProposalPending.Equals(other.EProposalPending)
                ) && 
                (
                    EProposalPendingApproval == other.EProposalPendingApproval ||
                    
                    EProposalPendingApproval.Equals(other.EProposalPendingApproval)
                ) && 
                (
                    NeNearEta == other.NeNearEta ||
                    
                    NeNearEta.Equals(other.NeNearEta)
                ) && 
                (
                    NeDispatchNotConfirmed == other.NeDispatchNotConfirmed ||
                    
                    NeDispatchNotConfirmed.Equals(other.NeDispatchNotConfirmed)
                ) && 
                (
                    NeDeclined == other.NeDeclined ||
                    
                    NeDeclined.Equals(other.NeDeclined)
                ) && 
                (
                    NeProposalPending == other.NeProposalPending ||
                    
                    NeProposalPending.Equals(other.NeProposalPending)
                ) && 
                (
                    NeProposalPendingApproval == other.NeProposalPendingApproval ||
                    
                    NeProposalPendingApproval.Equals(other.NeProposalPendingApproval)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    
                    hashCode = hashCode * 59 + ENearEta.GetHashCode();
                    
                    hashCode = hashCode * 59 + EDispatchNotConfirmed.GetHashCode();
                    
                    hashCode = hashCode * 59 + EDeclined.GetHashCode();
                    
                    hashCode = hashCode * 59 + EProposalPending.GetHashCode();
                    
                    hashCode = hashCode * 59 + EProposalPendingApproval.GetHashCode();
                    
                    hashCode = hashCode * 59 + NeNearEta.GetHashCode();
                    
                    hashCode = hashCode * 59 + NeDispatchNotConfirmed.GetHashCode();
                    
                    hashCode = hashCode * 59 + NeDeclined.GetHashCode();
                    
                    hashCode = hashCode * 59 + NeProposalPending.GetHashCode();
                    
                    hashCode = hashCode * 59 + NeProposalPendingApproval.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(SCServiceChannelServicesMessagingLandingUserLandingData left, SCServiceChannelServicesMessagingLandingUserLandingData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(SCServiceChannelServicesMessagingLandingUserLandingData left, SCServiceChannelServicesMessagingLandingUserLandingData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
