/*
 * ServiceChannel API - v.3
 *
 * The ServiceChannel API is a RESTful and stateless API. It accepts standard HTTP verbs and supports OAuth 2.0 for authorizing requests.      Our API returns common HTTP status codes as well as JSON encapsulated data.      See [API Overview](https://developer.servicechannel.com/basics/introduction/overview/) for the intro to ServiceChannel API.<br>      <h3>Authentication and Authorization</h3>You should have a ServiceChannel account, register your application, and obtain `access_token` to integrate with our API.      See [Authentication and Authorization](https://developer.servicechannel.com/basics/general/authentication/) for more information.      To use this API playground, click **Authorize** and sign in to ServiceChannel.<br>      <h3>Environment</h3> All calls in this API Reference point to the **SB2 environment**.      See [Environments](https://developer.servicechannel.com/basics/general/environments/) for more information.<br>      <h3>API Version</h3>The current stable version of the ServiceChannel API is `v3`. In the request URL, `v3` is a version prefix that should be present.      When you omit the version prefix, calls point to the minimum supported version of the API.      We recommend you to always specify the API version to avoid possible errors.
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ServiceChannel.Api.Model;
using ServiceChannel.Api.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ServiceChannel.Api.Test.Model
{
    /// <summary>
    ///  Class for testing SCServiceChannelServicesMessagingLandingUserLandingData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SCServiceChannelServicesMessagingLandingUserLandingDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SCServiceChannelServicesMessagingLandingUserLandingData
        //private SCServiceChannelServicesMessagingLandingUserLandingData instance;

        public SCServiceChannelServicesMessagingLandingUserLandingDataTests()
        {
            // TODO uncomment below to create an instance of SCServiceChannelServicesMessagingLandingUserLandingData
            //instance = new SCServiceChannelServicesMessagingLandingUserLandingData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SCServiceChannelServicesMessagingLandingUserLandingData
        /// </summary>
        [Fact]
        public void SCServiceChannelServicesMessagingLandingUserLandingDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SCServiceChannelServicesMessagingLandingUserLandingData
            //Assert.IsType<SCServiceChannelServicesMessagingLandingUserLandingData>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ENearEta'
        /// </summary>
        [Fact]
        public void ENearEtaTest()
        {
            // TODO unit test for the property 'ENearEta'
        }
        /// <summary>
        /// Test the property 'EDispatchNotConfirmed'
        /// </summary>
        [Fact]
        public void EDispatchNotConfirmedTest()
        {
            // TODO unit test for the property 'EDispatchNotConfirmed'
        }
        /// <summary>
        /// Test the property 'EDeclined'
        /// </summary>
        [Fact]
        public void EDeclinedTest()
        {
            // TODO unit test for the property 'EDeclined'
        }
        /// <summary>
        /// Test the property 'EProposalPending'
        /// </summary>
        [Fact]
        public void EProposalPendingTest()
        {
            // TODO unit test for the property 'EProposalPending'
        }
        /// <summary>
        /// Test the property 'EProposalPendingApproval'
        /// </summary>
        [Fact]
        public void EProposalPendingApprovalTest()
        {
            // TODO unit test for the property 'EProposalPendingApproval'
        }
        /// <summary>
        /// Test the property 'NeNearEta'
        /// </summary>
        [Fact]
        public void NeNearEtaTest()
        {
            // TODO unit test for the property 'NeNearEta'
        }
        /// <summary>
        /// Test the property 'NeDispatchNotConfirmed'
        /// </summary>
        [Fact]
        public void NeDispatchNotConfirmedTest()
        {
            // TODO unit test for the property 'NeDispatchNotConfirmed'
        }
        /// <summary>
        /// Test the property 'NeDeclined'
        /// </summary>
        [Fact]
        public void NeDeclinedTest()
        {
            // TODO unit test for the property 'NeDeclined'
        }
        /// <summary>
        /// Test the property 'NeProposalPending'
        /// </summary>
        [Fact]
        public void NeProposalPendingTest()
        {
            // TODO unit test for the property 'NeProposalPending'
        }
        /// <summary>
        /// Test the property 'NeProposalPendingApproval'
        /// </summary>
        [Fact]
        public void NeProposalPendingApprovalTest()
        {
            // TODO unit test for the property 'NeProposalPendingApproval'
        }

    }

}
